/*  DO NOT EDIT THIS FILE.

    It has been auto-edited by fixincludes from:

	"/home/iamedu/Compilers/arm-l4/arm-elf/sys-include/sys/types.h"

    This had to be done to correct non-standard usages in the
    original, manufacturer supplied header file.  */

#ifndef _TYPES_H
#define _TYPES_H

#ifndef _STDDEF_H_
#if !defined(_GCC_SIZE_T)
#define _GCC_SIZE_T
typedef __SIZE_TYPE__ size_t;
#endif

#endif

typedef unsigned long ssize_t;
#ifndef pid_t
typedef int pid_t;
#endif
typedef int off_t;
typedef int dev_t;
typedef int ino_t;
typedef int mode_t;
typedef int nlink_t;
typedef int uid_t;
typedef int gid_t;
typedef int blksize_t;
typedef int blkcnt_t;
typedef int time_t;
typedef int suseconds_t;

#endif

